using System.Text;
using SpDtoGen.Models;
using SpDtoGen.TypeMapping;

namespace SpDtoGen.Generators;

public class DtoCodeGenerator
{
    public string Generate(StoredProcedureInfo sp, GenerationOptions opts)
    {
        var className = DtoNameBuilder.Build(sp.Name, opts.DtoSuffix);
        var sb = new StringBuilder();

        AppendHeader(sb, sp);
        AppendUsings(sb, sp.Columns);
        sb.AppendLine();
        sb.AppendLine($"namespace {opts.Namespace};");
        sb.AppendLine();

        if (opts.AddGeneratedCodeAttribute)
        {
            sb.AppendLine("""[GeneratedCode("SpDtoGen", "1.0.0")]""");
        }

        // XML doc
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// DTO for stored procedure [{sp.Schema}].[{sp.Name}]");
        sb.AppendLine($"/// </summary>");

        var keyword = opts.UseRecord ? "record" : "class";
        sb.AppendLine($"public {keyword} {className}");
        sb.AppendLine("{");

        if (sp.HasUndescribableResultSet)
        {
            sb.AppendLine($"    // WARNING: {sp.UndescribableReason ?? "Result set could not be determined"}");
            sb.AppendLine($"    // Please add properties manually.");
        }
        else
        {
            foreach (var col in sp.Columns)
            {
                AppendProperty(sb, col);
            }
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendHeader(StringBuilder sb, StoredProcedureInfo sp)
    {
        sb.AppendLine($"// <auto-generated>");
        sb.AppendLine($"//   Generated by SpDtoGen on {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"//   Source SP: {sp.FullName}");
        sb.AppendLine($"// </auto-generated>");
        sb.AppendLine();
    }

    private void AppendUsings(StringBuilder sb, List<ColumnMetadata> columns)
    {
        var usings = new SortedSet<string> { "System.CodeDom.Compiler" };
        foreach (var col in columns) // conditionally add using based on types used
        {
            var type = SqlTypeToCSharpMapper.Map(col).TrimEnd('?');
            if (type is "DateOnly" or "TimeOnly" or "DateTime" or "DateTimeOffset")
                usings.Add("System"); // already implicit in net8 but explicit is safe
        }
        foreach (var u in usings)
            sb.AppendLine($"using {u};");
    }

    private void AppendProperty(StringBuilder sb, ColumnMetadata col)
    {
        var csharpType = SqlTypeToCSharpMapper.Map(col);
        var propName = ToPascalCase(col.Name);
  
        var decimalAnnotation = SqlTypeToCSharpMapper.GetDecimalAnnotation(col); // Decimal precision annotation
        if (decimalAnnotation is not null)
            sb.AppendLine($"    {decimalAnnotation}");
     
        var initializer = GetInitializer(csharpType, col); // Default value initializer for non-nullable reference types

        sb.AppendLine($"    public {csharpType} {propName} {{ get; set; }}{initializer}");
    }

    private static string GetInitializer(string csharpType, ColumnMetadata col)
    {       
        if (csharpType == "string") // non-nullable string needs an initializer to avoid CS8618
            return " = string.Empty;";

        if (csharpType == "byte[]")
            return " = [];";
    
        return string.Empty; // value types and nullable types don't need initializers
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
     
        if (!name.Contains('_')) // Already PascalCase (common in SQL): just ensure first char is upper
            return char.ToUpperInvariant(name[0]) + name[1..];
      
        return string.Concat( // Snake_case column names -> PascalCase
            name.Split('_', StringSplitOptions.RemoveEmptyEntries)
                .Select(s => char.ToUpperInvariant(s[0]) + s[1..])
        );
    }
}