// <auto-generated>
//   Generated by SpDtoGen on 2026-04-13 11:12:43 UTC
//   Source SP: [dbo].[TaiChinh_DSHoanTienTU]
//   Do not edit this file manually.
// </auto-generated>

using System;
using System.CodeDom.Compiler;

namespace Application.DTOs;

[GeneratedCode("SpDtoGen", "1.0.0")]
/// <summary>
/// DTO for stored procedure [dbo].[TaiChinh_DSHoanTienTU]
/// </summary>
public class TaiChinhDSHoanTienTUDto
{
    public long? IDVaoVien { get; set; }
    public double? SoTien { get; set; }
    public double? SOTIENSD { get; set; }
    public DateTime? Ngay { get; set; }
    public string MaVaoVien { get; set; } = string.Empty;
    public long IDBN { get; set; }
    public string MaBN { get; set; } = string.Empty;
    public string TenBN { get; set; } = string.Empty;
    public int? SoThuTuNgay { get; set; }
    public string NgaySinh { get; set; } = string.Empty;
    public string Tuoi { get; set; } = string.Empty;
    public string TenGioiTinh { get; set; } = string.Empty;
    public string DiaChi { get; set; } = string.Empty;
    public string Dienthoai { get; set; } = string.Empty;
    public string SoCCCD { get; set; } = string.Empty;
}
